@startuml
!include <C4/C4_Container>

Person(user, "Пользователь", "Пользователь социальной сети")

System(user_page, "Социальная сеть (главный сервис)", "Отвечает за клиентское API, регистрацию и аутентификацию пользователя")
System(statistics, "Сервис статистики", "Отвечает за подсчет лайков и просмотров")
System(posts_comments, "Сервис постов и комментариев", "Отвечает за создание, обновление, удаление постов и комментариев")

Rel(user, user_page, "Регистрируется/авторизуется и пользуется социальной сетью")
Rel(user_page, statistics, "Ведет статистику")
Rel(user_page, posts_comments, "Управляет постами и комментариями")

@enduml
