version: '3.9'

services:
  db:
    image: postgres:latest
    ports:
      - "5433"
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      PGPORT: 5433
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_config:/etc/postgresql
    networks:
      - postgres

  app:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend-app
    restart: always
    volumes:
      - ./backend:/backend
    ports:
        - '8000:8000'
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5433
      - DATABASE_PASSWORD=1234
      - DATABASE_NAME=users
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:1234@db:5433/users
      - JWT_SECRET_KEY=3d64e41e753e070ceee4525794d7fab1b2c6f2dc0e38495c04f2fc21c0078eace311fef8c56852dc2e46cb3433cf776c15c6d7dd2b527a4fb0e2b0906363fece
    depends_on:
      - db
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - postgres

networks:
  postgres:
    name : "postgres"

volumes:
  db_data:
  db_config:
  pgadmin-data: